#!/bin/bash

SOURCE_FILE="$1" 
SOURCE_FILE_NAME=${SOURCE_FILE%.*}
SOURCE_FILE_EXTENSION=${SOURCE_FILE##*.}
OUTPUT_FILE="${SOURCE_FILE_NAME}_prev.${SOURCE_FILE_EXTENSION}"
OUTPUT_FILE_LC=${OUTPUT_FILE,,}

cp -f -T $SOURCE_FILE $OUTPUT_FILE_LC

