#!/bin/bash

SCRIPTING_PATH="${HOME}/.gnome2/nautilus-scripts/redhound_scripting"
BASENAME=$(basename "${1}")
SOURCE_FILE="/tmp/.${BASENAME}"
BINARY_FILE="/tmp/.${BASENAME}.exe"
COMMON_SOURCE_FILE="${SCRIPTING_PATH}/.redhound_scripting.cs"
LOG_FILE="/tmp/.${BASENAME}.log"
PRINT_LOG="${SCRIPTING_PATH}/.show_log"

cat "${1}" | grep -v "/usr/bin/csrun" > "${SOURCE_FILE}"
rm -f "${BINARY_FILE}"
gmcs -r:System.Web -optimize+ -out:"${BINARY_FILE}" "${SOURCE_FILE}" "${COMMON_SOURCE_FILE}" &> "${LOG_FILE}";
$(x-terminal-emulator -e "${PRINT_LOG} ${LOG_FILE}")
rm -f "${SOURCE_FILE}"

